### ISSUE TITLE
Registrar um usuário sem um client associado causa erro 500

### ISSUE THREAD

**Issue by GCastilho** [PoultryTrader/api#35]
Ao registrar um usuário que já existe sem informar um cliente, ao invés de retornar 401 o servidor está crashando e retornando 500

Stack trace:

```
InternalServerError: PrismaClientValidationError: 
Invalid `prisma.user.create()` invocation in
/home/gabriel/Documentos/code/PoultryTrader/api/src/routes/v1/users.ts:20:21

  17 	client,
  18 	role,
  19 } = await validate(UserInput, req.body)
→ 20 await prisma.user.create({
       data: {
         email: 'castilhog@techagr.com',
         password: '$2a$08$y2Vy2ZKgVcAnyqD3gnURDO9W936Vtk7w8R8LtGOEE2EVUyXfb9bYS',
         role: 'ADMIN',
         client: {
         ~~~~~~
           connect: {
             name: undefined
           }
         }
       }
     })

Unknown arg `client` in data.client for type UserUncheckedCreateInput. Did you mean `clientId`? Available args:
type UserUncheckedCreateInput {
  id?: String
  clientId?: String | Null
  email: String
  password: String
  role?: UserRole
  createdAt?: DateTime
  updatedAt?: DateTime
}


    at Document.validate (/home/gabriel/Documentos/code/PoultryTrader/api/node_modules/@prisma/client/runtime/index.js:32448:19)
    at NewPrismaClient._executeRequest (/home/gabriel/Documentos/code/PoultryTrader/api/node_modules/@prisma/client/runtime/index.js:34385:17)
    at /home/gabriel/Documentos/code/PoultryTrader/api/node_modules/@prisma/client/runtime/index.js:34320:52
    at AsyncResource.runInAsyncScope (async_hooks.js:197:9)
    at NewPrismaClient._request (/home/gabriel/Documentos/code/PoultryTrader/api/node_modules/@prisma/client/runtime/index.js:34320:25)
    at Object.catch (/home/gabriel/Documentos/code/PoultryTrader/api/node_modules/@prisma/client/runtime/index.js:34471:39)
    at /home/gabriel/Documentos/code/PoultryTrader/api/src/routes/v1/users.ts:29:11 {
  clientVersion: '2.19.0'
}
```

**Comment by GCastilho** [comment]
A mesma coisa está acontecendo ao fazer login de um usuário que não existe

```
InternalServerError: PrismaClientKnownRequestError2 [PrismaClientKnownRequestError]: 
Invalid `prisma.user.findUnique()` invocation:


  The column `users.clientId` does not exist in the current database.
    at cb (/home/gabriel/Documentos/code/PoultryTrader/api/node_modules/@prisma/client/runtime/index.js:34774:17)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at /home/gabriel/Documentos/code/PoultryTrader/api/src/routes/v1/authentication.ts:23:16 {
  code: 'P2022',
  clientVersion: '2.19.0',
  meta: { column: 'users.clientId' }
}
```

**Comment by GCastilho** [comment]
Talvez seja um problema com o prisma, see prisma/prisma#6186

**Comment by GCastilho** [comment]
O problema do prisma não foi resolvido, então eu fiz um workaround que faz o prisma parar de crashar
